# version: "3.9"
---
services:
  backend:
    build: ./backend
    container_name: backend
    ports:
      - "8000:8000"
    env_file:
      - .env
    working_dir: /app
    depends_on:
      - db
      - redis
      - minio
      - spleeter
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
    user: "${PUID}:${PGID}"
    volumes:
      - ./audio_files:/app/audio_files  # ✅ Mounted inside working directory

  celery_worker:
    build: ./backend
    container_name: celery_worker
    command: celery -A app.celery_worker.celery_app worker --loglevel=info
    working_dir: /app
    depends_on:
      - redis
      - backend
    env_file:
      - .env
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
    user: "${PUID}:${PGID}"
    volumes:
      - ./audio_files:/app/audio_files  # ✅ Mounted inside working directory

  db:
    image: postgres:15
    container_name: postgres_db
    restart: always
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:latest
    container_name: redis_cache
    restart: always
    ports:
      - "6379:6379"

  minio:
    image: minio/minio
    container_name: minio_storage
    restart: always
    ports:
      - "9000:9000"
      - "9001:9001"
    env_file:
      - .env
    command: server /data --console-address ":9001"
    volumes:
      - minio_data:/data

  spleeter:
    build: ./spleeter_service
    container_name: spleeter
    ports:
      - "5001:5001"
    env_file:
      - .env
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - MODEL_DIR=/spleeter_service/pretrained_models
    user: "${PUID}:${PGID}"
    working_dir: /spleeter_service
    volumes:
#       - ./spleeter_models:/root/.cache/spleeter
      - ./spleeter_data:/spleeter_service/spleeter_audio
      - ./audio_files:/spleeter_service/audio_files
      - ./pretrained_models:/spleeter_service/pretrained_models  # ✅ Ensures correct ownership
    command: ["sh", "-c", "chown -R 1000:1000 /spleeter_service/pretrained_models && python3 -m uvicorn spleeter_api:app --host 0.0.0.0 --port 5001"]

volumes:
  postgres_data:
  minio_data:
  spleeter_data:
